name: Package Previews
on:
    pull_request:
        branches: [next, main]
        paths:
            - 'pnpm-lock.yaml'
            - 'packages/**'

jobs:
  release-previews:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
        - uses: actions/setup-node@v4
          with:
              node-version: "20"
              cache: pnpm

        - name: Install dependencies
          run: pnpm install # packages automatically built on postinstall

        - name: publish preview
          run: pnpm pkg-pr-new publish --pnpm './packages/jsrepo' './packages/mcp' './packages/transform-prettier' './packages/transform-biome' './packages/transform-javascript' './packages/migrate' --packageManager=pnpm